In [74]:
import os
import numpy as np
import polars as pl
import plotly.graph_objects as go
from sklearn.ensemble import IsolationForest

from snanomaly import dirs
import snanomaly.models.results.util as resutil
from snanomaly.models.results.util import explode_lists_to_numbered_columns
from snanomaly.models.sncandidate import Bandset
from snanomaly.preprocessing.band_transform import BandTransform

# Read data

In [5]:
dataset_name = "osc2018_june"

### Read non-reduced interpolated light curves

In [6]:
df_non_reduced = pl.read_parquet(dirs.INTERPOLATED / f"{dataset_name}_LSB-STATIC" / f"{dataset_name}.parquet")
df_non_reduced

shape: (1_572, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sn_name   ┆ bandset   ┆ peak_time ┆ days_pre_ ┆ … ┆ log_likel ┆ thetas    ┆ pred_mean ┆ pred_std │
│ ---       ┆ ---       ┆ ---       ┆ peak      ┆   ┆ ihood     ┆ ---       ┆ s         ┆ s        │
│ str       ┆ list[str] ┆ f64       ┆ ---       ┆   ┆ ---       ┆ list[f64] ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ i64       ┆   ┆ f64       ┆           ┆ list[list ┆ list[lis │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ [f64]]    ┆ t[f64]]  │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ SDSS-II   ┆ ["g_pr",  ┆ 54360.5   ┆ 20        ┆ … ┆ 40.859446 ┆ [1.817474 ┆ [[1.0836e ┆ [[3.1032 │
│ SN 17907  ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆ ,         ┆ -9, 1.721 ┆ e-8, 3.1 │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆ 0.976793, ┆ 6e-9, …   ┆ 026e-8,  │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 0.0]…     ┆ … 0.0]…  │
│           ┆           ┆           ┆           ┆   ┆           ┆ -0.1127…  ┆           ┆          │
│ SDSS-II   ┆ ["g_pr",  ┆ 54019.5   ┆ 20        ┆ … ┆ 20.305697 ┆ [1.040616 ┆ [[0.0,    ┆ [[0.0,   │
│ SN 15074  ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆ ,         ┆ 0.0, …    ┆ 0.0, …   │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆ 0.006335, ┆ 0.0],     ┆ 0.0],    │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ [0.0,     ┆ [0.0,    │
│           ┆           ┆           ┆           ┆   ┆           ┆ -0.1859…  ┆ 0.0,…     ┆ 0.0,…    │
│ PS1-12bku ┆ ["g_pr",  ┆ 56206.5   ┆ 20        ┆ … ┆ 5.712248  ┆ [1.485435 ┆ [[3.1984e ┆ [[3.0114 │
│           ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆ ,         ┆ -9, 4.025 ┆ e-9, 2.6 │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆ 1.028905, ┆ 3e-9, …   ┆ 499e-9,  │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 5.20…     ┆ … 3.54…  │
│           ┆           ┆           ┆           ┆   ┆           ┆ -0.2123…  ┆           ┆          │
│ PS1-12bku ┆ ["g",     ┆ 56174.5   ┆ 20        ┆ … ┆ 9.002704  ┆ [0.378619 ┆ [[1.1954e ┆ [[2.8726 │
│           ┆ "r", "i"] ┆           ┆           ┆   ┆           ┆ ,         ┆ -14, 2.51 ┆ e-9, 2.8 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0.112686, ┆ 98e-13, … ┆ 726e-9,  │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 3.…       ┆ … 2.87…  │
│           ┆           ┆           ┆           ┆   ┆           ┆ -4.6510…  ┆           ┆          │
│ SDSS-II   ┆ ["g_pr",  ┆ 54405.5   ┆ 20        ┆ … ┆ 26.328436 ┆ [1.245873 ┆ [[1.3023e ┆ [[4.7809 │
│ SN 20592  ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆ ,         ┆ -8, 1.162 ┆ e-13,    │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆ 1.124316, ┆ 3e-8, …   ┆ 1.8088e- │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 0.0]…     ┆ 10, …    │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0.19228…  ┆           ┆ 0.…      │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ SN2016ayf ┆ ["g",     ┆ 57464.5   ┆ 20        ┆ … ┆ 9.115077  ┆ [0.00002, ┆ [[6.7301e ┆ [[0.0000 │
│           ┆ "r", "i"] ┆           ┆           ┆   ┆           ┆ 0.000018, ┆ -93, 1.97 ┆ 02, 0.00 │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 89e-84, … ┆ 0002, …  │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0.054203… ┆ 0.…       ┆ 0.0], …  │
│ SN2007ai  ┆ ["g",     ┆ 54176.5   ┆ 20        ┆ … ┆ 61.49233  ┆ [1.616266 ┆ [[6.4079e ┆ [[2.1474 │
│           ┆ "r", "i"] ┆           ┆           ┆   ┆           ┆ ,         ┆ -10, 1.12 ┆ e-8, 2.1 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1.287578, ┆ 44e-9, …  ┆ 465e-8,  │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 7.3…      ┆ … 2.14…  │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0.04218…  ┆           ┆          │
│ PTF11dec  ┆ ["g",     ┆ 55704.5   ┆ 20        ┆ … ┆ 35.527299 ┆ [2.277329 ┆ [[2.8156e ┆ [[7.3147 │
│           ┆ "r", "i"] ┆           ┆           ┆   ┆           ┆ , 1.5342, ┆ -9, 3.358 ┆ e-9, 7.1 │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 9e-9, …   ┆ 975e-9,  │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0.059556] ┆ 0.0]…     ┆ … 0.0]…  │
│ SDSS-II   ┆ ["g_pr",  ┆ 53655.5   ┆ 20        ┆ … ┆ 1.032584  ┆ [1.044742 ┆ [[3.1993e ┆ [[1.4718 │
│ SN 3871   ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆ ,         ┆ -8, 3.647 ┆ e-9, 6.9 │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆ 0.567228, ┆ 2e-8, …   ┆ 247e-13, │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 0.0]…     ┆ … 0.0…   │
│           ┆           ┆           ┆           ┆   ┆           ┆ -0.1384…  ┆           ┆          │
│ SDSS-II   ┆ ["g_pr",  ┆ 53683.5   ┆ 20        ┆ … ┆ 14.990602 ┆ [1.15828, ┆ [[0.0,    ┆ [[0.0,   │
│ SN 11523  ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆ 0.928074, ┆ 0.0, …    ┆ 0.0, …   │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆ …         ┆ 0.0],     ┆ 0.0],    │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0.165242… ┆ [0.0,     ┆ [0.0,    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0.0,…     ┆ 0.0,…    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Read dimensionality-reduced data

In [71]:
dim_red_method = "TSNE"
dims = 2
df_reduced = pl.read_parquet(dirs.DIMREDUCED / dim_red_method / f"{dataset_name}_{dim_red_method}{dims}.parquet")
df_reduced

shape: (1_572, 3)
┌──────────────────┬──────────────────────────┬──────────────────────────┐
│ sn_name          ┆ bandset                  ┆ values                   │
│ ---              ┆ ---                      ┆ ---                      │
│ str              ┆ list[str]                ┆ list[f32]                │
╞══════════════════╪══════════════════════════╪══════════════════════════╡
│ SDSS-II SN 17907 ┆ ["g_pr", "r_pr", "i_pr"] ┆ [11.775729, -0.912904]   │
│ SDSS-II SN 15074 ┆ ["g_pr", "r_pr", "i_pr"] ┆ [7.939235, -0.23015]     │
│ PS1-12bku        ┆ ["g_pr", "r_pr", "i_pr"] ┆ [-45.086761, 13.524693]  │
│ PS1-12bku        ┆ ["g", "r", "i"]          ┆ [-13.744379, 7.033464]   │
│ SDSS-II SN 20592 ┆ ["g_pr", "r_pr", "i_pr"] ┆ [-32.976837, 10.518064]  │
│ …                ┆ …                        ┆ …                        │
│ SN2016ayf        ┆ ["g", "r", "i"]          ┆ [-42.538879, -27.932192] │
│ SN2007ai         ┆ ["g", "r", "i"]          ┆ [31.613644, -1.428256]   │
│ PTF11dec         ┆ ["g", "r", "i"]          ┆ [26.528658, -5.393352]   │
│ SDSS-II SN 3871  ┆ ["g_pr", "r_pr", "i_pr"] ┆ [21.38299, 37.262604]    │
│ SDSS-II SN 11523 ┆ ["g_pr", "r_pr", "i_pr"] ┆ [-21.514997, 3.635619]   │
└──────────────────┴──────────────────────────┴──────────────────────────┘

# Isolation Forest

In [11]:
isoforest = IsolationForest(n_estimators=1000, max_samples=1572, contamination=0.02, random_state=42)

In [21]:
X = explode_lists_to_numbered_columns(df_reduced, "values").select(pl.exclude(["sn_name", "bandset"]))
X

shape: (1_572, 2)
┌────────────┬────────────┐
│ values_0   ┆ values_1   │
│ ---        ┆ ---        │
│ f32        ┆ f32        │
╞════════════╪════════════╡
│ 11.775729  ┆ -0.912904  │
│ 7.939235   ┆ -0.23015   │
│ -45.086761 ┆ 13.524693  │
│ -13.744379 ┆ 7.033464   │
│ -32.976837 ┆ 10.518064  │
│ …          ┆ …          │
│ -42.538879 ┆ -27.932192 │
│ 31.613644  ┆ -1.428256  │
│ 26.528658  ┆ -5.393352  │
│ 21.38299   ┆ 37.262604  │
│ -21.514997 ┆ 3.635619   │
└────────────┴────────────┘

In [22]:
isoforest.fit(X)

IsolationForest(contamination=0.02, max_samples=1572, n_estimators=1000,
                random_state=42)

In [24]:
pred = isoforest.predict(X)
pred

array([1, 1, 1, ..., 1, 1, 1], shape=(1572,))

In [25]:
score = isoforest.score_samples(X)
score

array([-0.4655956 , -0.46100763, -0.53464558, ..., -0.46841271,
       -0.561278  , -0.47072059], shape=(1572,))

In [68]:
ind = sorted([i for i in range(pred.shape[0]) if pred[i] == -1], key=lambda x: score[x])
print("Outliers:")
out_df = df_reduced[ind].insert_column(3, pl.Series(name="anomaly_score", values=score[ind]))
out_df

Outliers:

shape: (32, 4)
┌──────────────────┬──────────────────────────┬──────────────────────────┬───────────────┐
│ sn_name          ┆ bandset                  ┆ values                   ┆ anomaly_score │
│ ---              ┆ ---                      ┆ ---                      ┆ ---           │
│ str              ┆ list[str]                ┆ list[f32]                ┆ f64           │
╞══════════════════╪══════════════════════════╪══════════════════════════╪═══════════════╡
│ SDSS-II SN 21386 ┆ ["g_pr", "r_pr", "i_pr"] ┆ [17.733162, 38.714638]   ┆ -0.628113     │
│ SDSS-II SN 6149  ┆ ["g_pr", "r_pr", "i_pr"] ┆ [-60.507946, -11.174562] ┆ -0.626443     │
│ SDSS-II SN 14221 ┆ ["g_pr", "r_pr", "i_pr"] ┆ [-60.420364, -11.288226] ┆ -0.621186     │
│ SDSS-II SN 2615  ┆ ["g_pr", "r_pr", "i_pr"] ┆ [54.833916, 8.463705]    ┆ -0.619367     │
│ SDSS-II SN 14552 ┆ ["g_pr", "r_pr", "i_pr"] ┆ [28.589369, 36.173809]   ┆ -0.615146     │
│ …                ┆ …                        ┆ …                        ┆ …             │
│ SN2009ib         ┆ ["g_pr", "r_pr", "i_pr"] ┆ [41.241882, -26.259424]  ┆ -0.584473     │
│ SDSS-II SN 13917 ┆ ["g_pr", "r_pr", "i_pr"] ┆ [6.288238, 34.011089]    ┆ -0.584407     │
│ SN2004dt         ┆ ["g", "r", "i"]          ┆ [-5.415148, -29.303276]  ┆ -0.584373     │
│ SDSS-II SN 18189 ┆ ["g_pr", "r_pr", "i_pr"] ┆ [8.067754, 35.668716]    ┆ -0.583374     │
│ SN2013dg         ┆ ["g", "r", "i"]          ┆ [45.718311, -25.859966]  ┆ -0.583102     │
└──────────────────┴──────────────────────────┴──────────────────────────┴───────────────┘

In [75]:
outlier_method = "ISOFOREST"
out_dir = dirs.ANOMALIES / outlier_method
os.makedirs(out_dir, exist_ok=True)

In [77]:
out_path = out_dir / f"{dataset_name}_{dim_red_method}{dims}_{outlier_method}.parquet"
out_df.select(pl.exclude("values")).write_parquet(out_path)

In [78]:
pl.read_parquet(out_path)

shape: (32, 3)
┌──────────────────┬──────────────────────────┬───────────────┐
│ sn_name          ┆ bandset                  ┆ anomaly_score │
│ ---              ┆ ---                      ┆ ---           │
│ str              ┆ list[str]                ┆ f64           │
╞══════════════════╪══════════════════════════╪═══════════════╡
│ SDSS-II SN 21386 ┆ ["g_pr", "r_pr", "i_pr"] ┆ -0.628113     │
│ SDSS-II SN 6149  ┆ ["g_pr", "r_pr", "i_pr"] ┆ -0.626443     │
│ SDSS-II SN 14221 ┆ ["g_pr", "r_pr", "i_pr"] ┆ -0.621186     │
│ SDSS-II SN 2615  ┆ ["g_pr", "r_pr", "i_pr"] ┆ -0.619367     │
│ SDSS-II SN 14552 ┆ ["g_pr", "r_pr", "i_pr"] ┆ -0.615146     │
│ …                ┆ …                        ┆ …             │
│ SN2009ib         ┆ ["g_pr", "r_pr", "i_pr"] ┆ -0.584473     │
│ SDSS-II SN 13917 ┆ ["g_pr", "r_pr", "i_pr"] ┆ -0.584407     │
│ SN2004dt         ┆ ["g", "r", "i"]          ┆ -0.584373     │
│ SDSS-II SN 18189 ┆ ["g_pr", "r_pr", "i_pr"] ┆ -0.583374     │
│ SN2013dg         ┆ ["g", "r", "i"]          ┆ -0.583102     │
└──────────────────┴──────────────────────────┴───────────────┘