# Read interpolated light curves

In [8]:
import numpy as np
import polars as pl
from sklearn.manifold import TSNE

from snanomaly import dirs
import snanomaly.models.results.util as resutil

In [9]:
# get input
dataset_name = "osc2018_june"
df = pl.read_parquet(dirs.INTERPOLATED / f"{dataset_name}_LSB-STATIC" / f"{dataset_name}.parquet")
df

shape: (1_572, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sn_name   ┆ bandset   ┆ peak_time ┆ days_pre_ ┆ … ┆ log_likel ┆ thetas    ┆ pred_mean ┆ pred_std │
│ ---       ┆ ---       ┆ ---       ┆ peak      ┆   ┆ ihood     ┆ ---       ┆ s         ┆ s        │
│ str       ┆ list[str] ┆ f64       ┆ ---       ┆   ┆ ---       ┆ list[f64] ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ i64       ┆   ┆ f64       ┆           ┆ list[list ┆ list[lis │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ [f64]]    ┆ t[f64]]  │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ SDSS-II   ┆ ["g_pr",  ┆ 54360.5   ┆ 20        ┆ … ┆ 40.859446 ┆ [1.817474 ┆ [[1.0836e ┆ [[3.1032 │
│ SN 17907  ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆ ,         ┆ -9, 1.721 ┆ e-8, 3.1 │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆ 0.976793, ┆ 6e-9, …   ┆ 026e-8,  │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 0.0]…     ┆ … 0.0]…  │
│           ┆           ┆           ┆           ┆   ┆           ┆ -0.1127…  ┆           ┆          │
│ SDSS-II   ┆ ["g_pr",  ┆ 54019.5   ┆ 20        ┆ … ┆ 20.305697 ┆ [1.040616 ┆ [[0.0,    ┆ [[0.0,   │
│ SN 15074  ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆ ,         ┆ 0.0, …    ┆ 0.0, …   │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆ 0.006335, ┆ 0.0],     ┆ 0.0],    │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ [0.0,     ┆ [0.0,    │
│           ┆           ┆           ┆           ┆   ┆           ┆ -0.1859…  ┆ 0.0,…     ┆ 0.0,…    │
│ PS1-12bku ┆ ["g_pr",  ┆ 56206.5   ┆ 20        ┆ … ┆ 5.712248  ┆ [1.485435 ┆ [[3.1984e ┆ [[3.0114 │
│           ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆ ,         ┆ -9, 4.025 ┆ e-9, 2.6 │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆ 1.028905, ┆ 3e-9, …   ┆ 499e-9,  │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 5.20…     ┆ … 3.54…  │
│           ┆           ┆           ┆           ┆   ┆           ┆ -0.2123…  ┆           ┆          │
│ PS1-12bku ┆ ["g",     ┆ 56174.5   ┆ 20        ┆ … ┆ 9.002704  ┆ [0.378619 ┆ [[1.1954e ┆ [[2.8726 │
│           ┆ "r", "i"] ┆           ┆           ┆   ┆           ┆ ,         ┆ -14, 2.51 ┆ e-9, 2.8 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0.112686, ┆ 98e-13, … ┆ 726e-9,  │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 3.…       ┆ … 2.87…  │
│           ┆           ┆           ┆           ┆   ┆           ┆ -4.6510…  ┆           ┆          │
│ SDSS-II   ┆ ["g_pr",  ┆ 54405.5   ┆ 20        ┆ … ┆ 26.328436 ┆ [1.245873 ┆ [[1.3023e ┆ [[4.7809 │
│ SN 20592  ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆ ,         ┆ -8, 1.162 ┆ e-13,    │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆ 1.124316, ┆ 3e-8, …   ┆ 1.8088e- │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 0.0]…     ┆ 10, …    │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0.19228…  ┆           ┆ 0.…      │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ SN2016ayf ┆ ["g",     ┆ 57464.5   ┆ 20        ┆ … ┆ 9.115077  ┆ [0.00002, ┆ [[6.7301e ┆ [[0.0000 │
│           ┆ "r", "i"] ┆           ┆           ┆   ┆           ┆ 0.000018, ┆ -93, 1.97 ┆ 02, 0.00 │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 89e-84, … ┆ 0002, …  │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0.054203… ┆ 0.…       ┆ 0.0], …  │
│ SN2007ai  ┆ ["g",     ┆ 54176.5   ┆ 20        ┆ … ┆ 61.49233  ┆ [1.616266 ┆ [[6.4079e ┆ [[2.1474 │
│           ┆ "r", "i"] ┆           ┆           ┆   ┆           ┆ ,         ┆ -10, 1.12 ┆ e-8, 2.1 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1.287578, ┆ 44e-9, …  ┆ 465e-8,  │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 7.3…      ┆ … 2.14…  │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0.04218…  ┆           ┆          │
│ PTF11dec  ┆ ["g",     ┆ 55704.5   ┆ 20        ┆ … ┆ 35.527299 ┆ [2.277329 ┆ [[2.8156e ┆ [[7.3147 │
│           ┆ "r", "i"] ┆           ┆           ┆   ┆           ┆ , 1.5342, ┆ -9, 3.358 ┆ e-9, 7.1 │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 9e-9, …   ┆ 975e-9,  │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0.059556] ┆ 0.0]…     ┆ … 0.0]…  │
│ SDSS-II   ┆ ["g_pr",  ┆ 53655.5   ┆ 20        ┆ … ┆ 1.032584  ┆ [1.044742 ┆ [[3.1993e ┆ [[1.4718 │
│ SN 3871   ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆ ,         ┆ -8, 3.647 ┆ e-9, 6.9 │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆ 0.567228, ┆ 2e-8, …   ┆ 247e-13, │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 0.0]…     ┆ … 0.0…   │
│           ┆           ┆           ┆           ┆   ┆           ┆ -0.1384…  ┆           ┆          │
│ SDSS-II   ┆ ["g_pr",  ┆ 53683.5   ┆ 20        ┆ … ┆ 14.990602 ┆ [1.15828, ┆ [[0.0,    ┆ [[0.0,   │
│ SN 11523  ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆ 0.928074, ┆ 0.0, …    ┆ 0.0, …   │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆ …         ┆ 0.0],     ┆ 0.0],    │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0.165242… ┆ [0.0,     ┆ [0.0,    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0.0,…     ┆ 0.0,…    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Prepare data for learning algorithms

In [10]:
# select columns of interest
light_curves = df.select(["sn_name", "bandset", "pred_means", "log_likelihood", "thetas"])

In [11]:
# normalize, standardize
light_curves = light_curves.with_columns(
    # normalize prediction mean values per candidate by the maximum of flux maximums
    pl.col("pred_means").map_elements(lambda x: x / max((xx.max() for xx in x)), return_dtype=list[list[float]]),
    # normalize theta values per candidate by the difference between maximum and minimum values
    pl.col("thetas").map_elements(lambda x: x / (x.max() - x.min()), return_dtype=list[float]),
    # standardize log-likelihood across all candidates
    (pl.col("log_likelihood") - pl.col("log_likelihood").mean()) / pl.col("log_likelihood").std(),
)
light_curves
# TODO: transform flux values to `gri` if band set is not `gri`

shape: (1_572, 5)
┌──────────────────┬────────────────────┬────────────────────┬────────────────┬────────────────────┐
│ sn_name          ┆ bandset            ┆ pred_means         ┆ log_likelihood ┆ thetas             │
│ ---              ┆ ---                ┆ ---                ┆ ---            ┆ ---                │
│ str              ┆ list[str]          ┆ list[list[f64]]    ┆ f64            ┆ list[f64]          │
╞══════════════════╪════════════════════╪════════════════════╪════════════════╪════════════════════╡
│ SDSS-II SN 17907 ┆ ["g_pr", "r_pr",   ┆ [[0.008535,        ┆ -0.068946      ┆ [0.941572,         │
│                  ┆ "i_pr"]            ┆ 0.013561, … 0.0],  ┆                ┆ 0.506043, …        │
│                  ┆                    ┆ …                  ┆                ┆ -0.0584…           │
│ SDSS-II SN 15074 ┆ ["g_pr", "r_pr",   ┆ [[0.0, 0.0, …      ┆ -0.404479      ┆ [0.81677,          │
│                  ┆ "i_pr"]            ┆ 0.0], [0.0, 0.0,…  ┆                ┆ 0.004972, …        │
│                  ┆                    ┆                    ┆                ┆ -0.14593…          │
│ PS1-12bku        ┆ ["g_pr", "r_pr",   ┆ [[0.307964,        ┆ -0.642712      ┆ [0.874917,         │
│                  ┆ "i_pr"]            ┆ 0.387573, …        ┆                ┆ 0.606022, …        │
│                  ┆                    ┆ 5.0152…            ┆                ┆ -0.1250…           │
│ PS1-12bku        ┆ ["g", "r", "i"]    ┆ [[0.000001,        ┆ -0.588997      ┆ [0.558184,         │
│                  ┆                    ┆ 0.000025, …        ┆                ┆ 0.166129, …        │
│                  ┆                    ┆ 3.2528…            ┆                ┆ -6.8568…           │
│ SDSS-II SN 20592 ┆ ["g_pr", "r_pr",   ┆ [[0.26558,         ┆ -0.30616       ┆ [1.182503,         │
│                  ┆ "i_pr"]            ┆ 0.237046, … 0.0],  ┆                ┆ 1.067128, …        │
│                  ┆                    ┆ […                 ┆                ┆ 0.18250…           │
│ …                ┆ …                  ┆ …                  ┆ …              ┆ …                  │
│ SN2016ayf        ┆ ["g", "r", "i"]    ┆ [[1.2671e-87,      ┆ -0.587162      ┆ [0.000036,         │
│                  ┆                    ┆ 3.7256e-79, … 0.…  ┆                ┆ 0.000032, …        │
│                  ┆                    ┆                    ┆                ┆ 0.09804…           │
│ SN2007ai         ┆ ["g", "r", "i"]    ┆ [[0.006907,        ┆ 0.267879       ┆ [1.026802,         │
│                  ┆                    ┆ 0.01212, …         ┆                ┆ 0.817989, …        │
│                  ┆                    ┆ 0.00008…           ┆                ┆ 0.02680…           │
│ PTF11dec         ┆ ["g", "r", "i"]    ┆ [[0.102895,        ┆ -0.155991      ┆ [1.026854,         │
│                  ┆                    ┆ 0.122751, … 0.0],  ┆                ┆ 0.691775, …        │
│                  ┆                    ┆ …                  ┆                ┆ 0.02685…           │
│ SDSS-II SN 3871  ┆ ["g_pr", "r_pr",   ┆ [[0.462006,        ┆ -0.719106      ┆ [0.813163,         │
│                  ┆ "i_pr"]            ┆ 0.526687, … 0.0],  ┆                ┆ 0.441495, …        │
│                  ┆                    ┆ …                  ┆                ┆ -0.1077…           │
│ SDSS-II SN 11523 ┆ ["g_pr", "r_pr",   ┆ [[0.0, 0.0, …      ┆ -0.491246      ┆ [1.1664, 0.934581, │
│                  ┆ "i_pr"]            ┆ 0.0], [0.0, 0.0,…  ┆                ┆ … 0.1664]          │
└──────────────────┴────────────────────┴────────────────────┴────────────────┴────────────────────┘

In [12]:
# converting list elements to columns
light_curves = resutil.explode_lists_to_numbered_columns(light_curves, "pred_means")
light_curves = resutil.explode_lists_to_numbered_columns(light_curves, "thetas")
light_curves

shape: (1_572, 375)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ sn_name   ┆ bandset   ┆ log_likel ┆ pred_mean ┆ … ┆ thetas_5  ┆ thetas_6 ┆ thetas_7  ┆ thetas_8  │
│ ---       ┆ ---       ┆ ihood     ┆ s_0       ┆   ┆ ---       ┆ ---      ┆ ---       ┆ ---       │
│ str       ┆ list[str] ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64      ┆ f64       ┆ f64       │
│           ┆           ┆ f64       ┆ f64       ┆   ┆           ┆          ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ SDSS-II   ┆ ["g_pr",  ┆ -0.068946 ┆ 0.008535  ┆ … ┆ 0.063746  ┆ 0.181604 ┆ 0.062441  ┆ -0.058428 │
│ SN 17907  ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ SDSS-II   ┆ ["g_pr",  ┆ -0.404479 ┆ 0.0       ┆ … ┆ -0.147243 ┆ 0.342232 ┆ -0.18323  ┆ -0.145935 │
│ SN 15074  ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ PS1-12bku ┆ ["g_pr",  ┆ -0.642712 ┆ 0.307964  ┆ … ┆ -0.077728 ┆ 0.361759 ┆ -0.064894 ┆ -0.125083 │
│           ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ PS1-12bku ┆ ["g",     ┆ -0.588997 ┆ 0.000001  ┆ … ┆ 0.118018  ┆ 1.0      ┆ 0.181948  ┆ -6.8568e- │
│           ┆ "r", "i"] ┆           ┆           ┆   ┆           ┆          ┆           ┆ 9         │
│ SDSS-II   ┆ ["g_pr",  ┆ -0.30616  ┆ 0.26558   ┆ … ┆ 0.1913    ┆ 0.31252  ┆ 0.22837   ┆ 0.182503  │
│ SN 20592  ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ SN2016ayf ┆ ["g",     ┆ -0.587162 ┆ 1.2671e-8 ┆ … ┆ 0.298598  ┆ 0.565231 ┆ 0.288839  ┆ 0.098048  │
│           ┆ "r", "i"] ┆           ┆ 7         ┆   ┆           ┆          ┆           ┆           │
│ SN2007ai  ┆ ["g",     ┆ 0.267879  ┆ 0.006907  ┆ … ┆ 0.08052   ┆ 0.187207 ┆ 0.085193  ┆ 0.026802  │
│           ┆ "r", "i"] ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ PTF11dec  ┆ ["g",     ┆ -0.155991 ┆ 0.102895  ┆ … ┆ 0.039185  ┆ 0.184766 ┆ 0.058749  ┆ 0.026854  │
│           ┆ "r", "i"] ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ SDSS-II   ┆ ["g_pr",  ┆ -0.719106 ┆ 0.462006  ┆ … ┆ -0.186837 ┆ 0.377902 ┆ -0.066476 ┆ -0.107766 │
│ SN 3871   ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ SDSS-II   ┆ ["g_pr",  ┆ -0.491246 ┆ 0.0       ┆ … ┆ 0.323722  ┆ 0.251482 ┆ 0.287413  ┆ 0.1664    │
│ SN 11523  ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

# t-SNE

In [13]:
def square_distance(X1: np.ndarray, X2: np.ndarray) -> np.ndarray:
    return np.sum((X1 - X2) ** 2)

tsne = TSNE(n_components=)

SyntaxError: expected argument value expression (2145521979.py, line 4)

# UMAP

In [ ]:
num_obs = len(df.select(["pred_means"][0])[0])
num_obs