# Read interpolated light curves

In [1]:
from snanomaly.dataset.factory import OSCFactory
from snanomaly import dirs
import numpy as np
import polars as pl
from sklearn.manifold import TSNE

from snanomaly.models.results.exception import UnexpectedDataFrameColumnError, EmptyDataFrameError
from snanomaly.models.results.mgp_result import MGPResult


def read_df(path: str) -> pl.DataFrame:
    print(f"Reading from: {path}")
    return pl.scan_parquet(path).collect()

In [2]:
dataset_name = "osc2018_june"
df = read_df(dirs.INTERPOLATED / f"{dataset_name}_LSB-STATIC" / f"{dataset_name}.parquet")
df

Reading from: /home/chongy/stuff/workspace/snanomaly/outputs/interpolated/osc2018_june_LSB-STATIC/osc2018_june.parquet

shape: (1_572, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sn_name   ┆ bandset   ┆ peak_time ┆ days_pre_ ┆ … ┆ log_likel ┆ thetas    ┆ pred_mean ┆ pred_std │
│ ---       ┆ ---       ┆ ---       ┆ peak      ┆   ┆ ihood     ┆ ---       ┆ s         ┆ s        │
│ str       ┆ list[str] ┆ f64       ┆ ---       ┆   ┆ ---       ┆ list[f64] ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ i64       ┆   ┆ f64       ┆           ┆ list[list ┆ list[lis │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ [f64]]    ┆ t[f64]]  │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ SDSS-II   ┆ ["g_pr",  ┆ 54360.5   ┆ 20        ┆ … ┆ 40.859446 ┆ [1.817474 ┆ [[1.0836e ┆ [[3.1032 │
│ SN 17907  ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆ ,         ┆ -9, 1.721 ┆ e-8, 3.1 │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆ 0.976793, ┆ 6e-9, …   ┆ 026e-8,  │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 0.0]…     ┆ … 0.0]…  │
│           ┆           ┆           ┆           ┆   ┆           ┆ -0.1127…  ┆           ┆          │
│ SDSS-II   ┆ ["g_pr",  ┆ 54019.5   ┆ 20        ┆ … ┆ 20.305697 ┆ [1.040616 ┆ [[0.0,    ┆ [[0.0,   │
│ SN 15074  ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆ ,         ┆ 0.0, …    ┆ 0.0, …   │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆ 0.006335, ┆ 0.0],     ┆ 0.0],    │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ [0.0,     ┆ [0.0,    │
│           ┆           ┆           ┆           ┆   ┆           ┆ -0.1859…  ┆ 0.0,…     ┆ 0.0,…    │
│ PS1-12bku ┆ ["g_pr",  ┆ 56206.5   ┆ 20        ┆ … ┆ 5.712248  ┆ [1.485435 ┆ [[3.1984e ┆ [[3.0114 │
│           ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆ ,         ┆ -9, 4.025 ┆ e-9, 2.6 │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆ 1.028905, ┆ 3e-9, …   ┆ 499e-9,  │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 5.20…     ┆ … 3.54…  │
│           ┆           ┆           ┆           ┆   ┆           ┆ -0.2123…  ┆           ┆          │
│ PS1-12bku ┆ ["g",     ┆ 56174.5   ┆ 20        ┆ … ┆ 9.002704  ┆ [0.378619 ┆ [[1.1954e ┆ [[2.8726 │
│           ┆ "r", "i"] ┆           ┆           ┆   ┆           ┆ ,         ┆ -14, 2.51 ┆ e-9, 2.8 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0.112686, ┆ 98e-13, … ┆ 726e-9,  │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 3.…       ┆ … 2.87…  │
│           ┆           ┆           ┆           ┆   ┆           ┆ -4.6510…  ┆           ┆          │
│ SDSS-II   ┆ ["g_pr",  ┆ 54405.5   ┆ 20        ┆ … ┆ 26.328436 ┆ [1.245873 ┆ [[1.3023e ┆ [[4.7809 │
│ SN 20592  ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆ ,         ┆ -8, 1.162 ┆ e-13,    │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆ 1.124316, ┆ 3e-8, …   ┆ 1.8088e- │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 0.0]…     ┆ 10, …    │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0.19228…  ┆           ┆ 0.…      │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ SN2016ayf ┆ ["g",     ┆ 57464.5   ┆ 20        ┆ … ┆ 9.115077  ┆ [0.00002, ┆ [[6.7301e ┆ [[0.0000 │
│           ┆ "r", "i"] ┆           ┆           ┆   ┆           ┆ 0.000018, ┆ -93, 1.97 ┆ 02, 0.00 │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 89e-84, … ┆ 0002, …  │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0.054203… ┆ 0.…       ┆ 0.0], …  │
│ SN2007ai  ┆ ["g",     ┆ 54176.5   ┆ 20        ┆ … ┆ 61.49233  ┆ [1.616266 ┆ [[6.4079e ┆ [[2.1474 │
│           ┆ "r", "i"] ┆           ┆           ┆   ┆           ┆ ,         ┆ -10, 1.12 ┆ e-8, 2.1 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1.287578, ┆ 44e-9, …  ┆ 465e-8,  │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 7.3…      ┆ … 2.14…  │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0.04218…  ┆           ┆          │
│ PTF11dec  ┆ ["g",     ┆ 55704.5   ┆ 20        ┆ … ┆ 35.527299 ┆ [2.277329 ┆ [[2.8156e ┆ [[7.3147 │
│           ┆ "r", "i"] ┆           ┆           ┆   ┆           ┆ , 1.5342, ┆ -9, 3.358 ┆ e-9, 7.1 │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 9e-9, …   ┆ 975e-9,  │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0.059556] ┆ 0.0]…     ┆ … 0.0]…  │
│ SDSS-II   ┆ ["g_pr",  ┆ 53655.5   ┆ 20        ┆ … ┆ 1.032584  ┆ [1.044742 ┆ [[3.1993e ┆ [[1.4718 │
│ SN 3871   ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆ ,         ┆ -8, 3.647 ┆ e-9, 6.9 │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆ 0.567228, ┆ 2e-8, …   ┆ 247e-13, │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆ 0.0]…     ┆ … 0.0…   │
│           ┆           ┆           ┆           ┆   ┆           ┆ -0.1384…  ┆           ┆          │
│ SDSS-II   ┆ ["g_pr",  ┆ 53683.5   ┆ 20        ┆ … ┆ 14.990602 ┆ [1.15828, ┆ [[0.0,    ┆ [[0.0,   │
│ SN 11523  ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆ 0.928074, ┆ 0.0, …    ┆ 0.0, …   │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆ …         ┆ 0.0],     ┆ 0.0],    │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0.165242… ┆ [0.0,     ┆ [0.0,    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0.0,…     ┆ 0.0,…    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# t-SNE

In [15]:
def square_distance(X1: np.ndarray, X2: np.ndarray) -> np.ndarray:
    return np.sum((X1 - X2) ** 2)

def rename_numbered_columns(df: pl.DataFrame, new_col_prefix: str) -> pl.DataFrame:
    numeric_cols = [col for col in df.columns if col.isdigit()]
    rename_dict = {col: f"{new_col_prefix}_{col}" for col in numeric_cols}
    return df.rename(rename_dict)

def lists_to_numbered_columns(df: pl.DataFrame, target_col: str) -> pl.DataFrame:
    """Flattens lists of up to 2D lists into columns."""
    # get list dimensions
    first_row = df[target_col][0]
    if isinstance(first_row, pl.Series):
        if isinstance(first_row[0], float):
            num_lists = 1
            list_length = len(first_row)
        elif isinstance(first_row[0], pl.Series):
            num_lists = len(first_row)
            list_length = len(first_row[0])
        else:
            raise UnexpectedDataFrameColumnError(f"Column `{target_col}` must be of type 1D list or 2D list.")
    else:
        raise EmptyDataFrameError(f"No rows in data frame with columns: `{df.columns}`")
    # explode lists until there are no more lists
    nr_dimensions = 1 if num_lists == 1 else 2
    for i in range(nr_dimensions):
        df = df.explode(columns=[target_col])
    df = df.with_row_index(name="col_nr").with_columns(pl.col("col_nr").mod(num_lists * list_length)).pivot(on="col_nr", values=[target_col])
    return rename_numbered_columns(df, target_col)

In [17]:
light_curves = df.select(["sn_name", "bandset", "pred_means", "log_likelihood", "thetas"])
# TODO: band transform if band set differs from `gri`

# transform `pred_means` list of lists into as many columns as there are list elements
light_curves = lists_to_numbered_columns(light_curves, "pred_means")
# transform `thetas` list into columns
light_curves = lists_to_numbered_columns(light_curves, "thetas")
light_curves
# normalize `pred_means` list by flux vector maximum across the bandset

shape: (1_572, 375)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ sn_name   ┆ bandset   ┆ log_likel ┆ pred_mean ┆ … ┆ thetas_5  ┆ thetas_6 ┆ thetas_7  ┆ thetas_8  │
│ ---       ┆ ---       ┆ ihood     ┆ s_0       ┆   ┆ ---       ┆ ---      ┆ ---       ┆ ---       │
│ str       ┆ list[str] ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64      ┆ f64       ┆ f64       │
│           ┆           ┆ f64       ┆ f64       ┆   ┆           ┆          ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ SDSS-II   ┆ ["g_pr",  ┆ 40.859446 ┆ 1.0836e-9 ┆ … ┆ 0.123047  ┆ 0.350543 ┆ 0.120528  ┆ -0.112782 │
│ SN 17907  ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ SDSS-II   ┆ ["g_pr",  ┆ 20.305697 ┆ 0.0       ┆ … ┆ -0.187596 ┆ 0.436024 ┆ -0.233446 ┆ -0.185931 │
│ SN 15074  ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ PS1-12bku ┆ ["g_pr",  ┆ 5.712248  ┆ 3.1984e-9 ┆ … ┆ -0.131967 ┆ 0.614195 ┆ -0.110177 ┆ -0.212365 │
│           ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ PS1-12bku ┆ ["g",     ┆ 9.002704  ┆ 1.1954e-1 ┆ … ┆ 0.080052  ┆ 0.678304 ┆ 0.123416  ┆ -4.6510e- │
│           ┆ "r", "i"] ┆           ┆ 4         ┆   ┆           ┆          ┆           ┆ 9         │
│ SDSS-II   ┆ ["g_pr",  ┆ 26.328436 ┆ 1.3023e-8 ┆ … ┆ 0.201551  ┆ 0.329268 ┆ 0.240609  ┆ 0.192283  │
│ SN 20592  ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ SN2016ayf ┆ ["g",     ┆ 9.115077  ┆ 6.7301e-9 ┆ … ┆ 0.165072  ┆ 0.312472 ┆ 0.159676  ┆ 0.054203  │
│           ┆ "r", "i"] ┆           ┆ 3         ┆   ┆           ┆          ┆           ┆           │
│ SN2007ai  ┆ ["g",     ┆ 61.49233  ┆ 6.4079e-1 ┆ … ┆ 0.126745  ┆ 0.294678 ┆ 0.134101  ┆ 0.042188  │
│           ┆ "r", "i"] ┆           ┆ 0         ┆   ┆           ┆          ┆           ┆           │
│ PTF11dec  ┆ ["g",     ┆ 35.527299 ┆ 2.8156e-9 ┆ … ┆ 0.086902  ┆ 0.409769 ┆ 0.130292  ┆ 0.059556  │
│           ┆ "r", "i"] ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ SDSS-II   ┆ ["g_pr",  ┆ 1.032584  ┆ 3.1993e-8 ┆ … ┆ -0.240047 ┆ 0.485525 ┆ -0.085407 ┆ -0.138456 │
│ SN 3871   ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ SDSS-II   ┆ ["g_pr",  ┆ 14.990602 ┆ 0.0       ┆ … ┆ 0.321468  ┆ 0.249731 ┆ 0.285412  ┆ 0.165242  │
│ SN 11523  ┆ "r_pr",   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆ "i_pr"]   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [ ]:
tsne = TSNE(n_components=)

# UMAP

In [131]:
num_obs = len(df.select(["pred_means"][0])[0])
num_obs

1